"""Editorial summaries of retrieved primary sources, checked 4 October 2026.
Reported outcomes belong to the cited sources, not AdaptTrail users.
"""
DOCUMENTED_PROJECTS = [
 dict(id='niger-tahoua',title='Restoring land in Tahoua',country='Niger',action='Land restoration',setting='Tahoua region',
      problem='Degraded land threatens rural livelihoods in the Sahel.',
      approach='The PGIP programme combines half-moon catchments, assisted natural regeneration and invasive-plant control with community planning.',
      outcome='The World Bank’s August 2025 account reports about 18,000 hectares restored in Tahoua and natural regeneration on 10,500 hectares. These categories are not added together here.',
      limitation='Programme reporting, adapted from a Nigerien news agency account; not a controlled evaluation or a forecast for another farm.',
      conditions='Check land rights, runoff, soil, labour and local restoration expertise before choosing a small trial.',
      lessons='Record the trial area, survival of plants, maintenance work and observations through wet and dry periods.',
      publisher='World Bank',source_date='2025-08-14',source_title='Restoring Land and Livelihoods in Niger’s Tahoua Region',
      source_url='https://www.worldbank.org/en/brief/2025/08/14/restoring-land-and-livelihoods-in-niger-s-tahoua-region'),
 dict(id='burkina-stone-bunds',title='Contour stone bunds in Yatenga',country='Burkina Faso',action='Runoff harvesting',setting='Yatenga Province',
      problem='Dry conditions and crusted, degraded fields limit crop production.',
      approach='An agroforestry project trained farmers to align stone bunds along contours. FAO also describes using planting pits and manure with bunds on degraded land.',
      outcome='FAO’s historical case reports treated land expanding from 150 hectares in 1982 to approximately 5,000 in 1987, with higher cereal yields reported for participating farmers.',
      limitation='A 1991 manual describing historical experience; this does not establish current performance or a controlled comparison.',
      conditions='Check slope, stone supply, transport, labour and fertility with local agricultural guidance. This summary is not a construction design.',
      lessons='Record labour, material transport, repairs, runoff and crop observations on a modest trial.',
      publisher='FAO',source_date='1991 (publication year)',source_title='Water harvesting, section 5.7: Contour stone bunds',
      source_url='https://www.fao.org/4/u3160e/u3160e07.htm'),
 dict(id='nigeria-newmap',title='Managing erosion through NEWMAP',country='Nigeria',action='Erosion management',setting='Targeted Nigerian catchments',
      problem='Gully erosion and climate hazards threaten land and communities.',
      approach='NEWMAP combined catchment planning, erosion-risk mapping, hydrometeorological monitoring and rehabilitation of eroded gullies.',
      outcome='A January 2021 World Bank blog reports improved erosion maps and catchment plans in 16 states and installation of 75 hydrometeorological stations.',
      limitation='An institutional overview reporting programme outputs; it does not establish a household-level benefit or prove that every intervention succeeded.',
      conditions='Coordinate with local authorities and qualified specialists. Gully works require catchment-level assessment, permissions and maintenance.',
      lessons='Document erosion observations and who maintains the site. Do not enter unstable gullies to collect records.',
      publisher='World Bank',source_date='2021-01-11',source_title='Building corridors of growth through the Sahel and beyond',
      source_url='https://blogs.worldbank.org/en/nasikiliza/building-corridors-growth-through-sahel-and-beyond'),
 dict(id='ethiopia-calm',title='Community watershed restoration through CALM',country='Ethiopia',action='Land restoration',setting='Ethiopian highlands',
      problem='Eroded hillsides and insecure land rights discourage long-term restoration.',
      approach='CALM combines soil and water conservation and landscape management with land certification and community watershed institutions.',
      outcome='The World Bank’s June 2026 feature reports over 2.56 million hectares under sustainable landscape management, with results described as achieved by September 2025.',
      limitation='An institutional programme account. Area under management is not the same as measured crop-yield improvement or proven displacement reduction.',
      conditions='Check land tenure, community agreements, slope, maintenance responsibilities and technical support.',
      lessons='Record agreed responsibilities, the area treated and changes observed over time.',
      publisher='World Bank',source_date='2026-06-15',source_title='From Degraded Hillsides to Productive Land: Ethiopia’s Landscape Management Program',
      source_url='https://www.worldbank.org/en/news/feature/2026/06/15/from-degraded-hillsides-to-productive-land-ethiopia-s-landscape-management-program'),
 dict(id='bangladesh-floating',title='Floating gardens in flood-prone wetlands',country='Bangladesh',action='Flood-adapted farming',setting='Southern and south-western wetlands',
      problem='Long-lasting inundation makes conventional field cultivation difficult.',
      approach='Farmers use floating beds of water hyacinth and other plant residues to cultivate crops in waterlogged areas.',
      outcome='FAO documents an established indigenous production system and lists its heritage status as designated. The linked page does not provide a quantified yield increase.',
      limitation='A heritage-system description rather than a controlled impact study. The page is undated; its listed start date is not its publication date.',
      conditions='Seek local advice on water quality, flood behaviour, access, anchoring, crop needs and handling aquatic plants.',
      lessons='Record materials, maintenance, crop condition and flood-related difficulties without treating the bed as flood protection.',
      publisher='FAO',source_date='Not stated on source page',source_title='Floating Garden Agricultural Practices',
      source_url='https://www.fao.org/giahs/around-the-world/detail/bangladesh-floating-gardens-system/'),
 dict(id='india-cool-roofs',title='Cool roofs within Ahmedabad’s heat plan',country='India',action='Urban heat adaptation',setting='Ahmedabad',
      problem='Urban heat disproportionately affects households with limited cooling options.',
      approach='Ahmedabad’s Heat Action Plan includes reflective roofs, early warning, public water supplies and vegetation.',
      outcome='UNEP’s July 2020 account reports white-painted roofs at around 7,000 low-income households. This is coverage reported at that time, not current uptake.',
      limitation='A city-plan account, not a controlled roof-only study. Benefits of the whole heat plan must not be attributed to roofs alone.',
      conditions='Check roof condition, suitable materials, permissions, maintenance and local building advice. Never access an unsafe roof.',
      lessons='Record indoor conditions, shade, ventilation and coating maintenance alongside local weather.',
      publisher='UNEP',source_date='2020-07-22',source_title='How cities are using nature to keep heatwaves at bay',
      source_url='https://www.unep.org/news-and-stories/story/how-cities-are-using-nature-keep-heatwaves-bay'),
]
for project in DOCUMENTED_PROJECTS:
    project.update(kind='documented', checked_at='2026-10-04')
