CREATE TABLE adapttrail_private.publications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL UNIQUE REFERENCES adapttrail_private.drafts(id) ON DELETE CASCADE,
 title TEXT NOT NULL,country TEXT NOT NULL,problem TEXT NOT NULL,
 action TEXT NOT NULL,outcome TEXT NOT NULL,lessons TEXT NOT NULL,
 published INTEGER NOT NULL DEFAULT 1,hidden INTEGER NOT NULL DEFAULT 0,
 updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE adapttrail_private.story_reports (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 publication_id BIGINT NOT NULL REFERENCES adapttrail_private.publications(id) ON DELETE CASCADE,
 reason TEXT NOT NULL,resolved INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX reports_publication ON adapttrail_private.story_reports(publication_id);
ALTER TABLE adapttrail_private.publications ENABLE ROW LEVEL SECURITY;
ALTER TABLE adapttrail_private.story_reports ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON adapttrail_private.publications,adapttrail_private.story_reports FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON adapttrail_private.publications,adapttrail_private.story_reports TO adapttrail_app;
GRANT USAGE,SELECT ON SEQUENCE adapttrail_private.publications_id_seq,adapttrail_private.story_reports_id_seq TO adapttrail_app;
CREATE POLICY backend_access ON adapttrail_private.publications FOR ALL TO adapttrail_app USING(true) WITH CHECK(true);
CREATE POLICY backend_access ON adapttrail_private.story_reports FOR ALL TO adapttrail_app USING(true) WITH CHECK(true);
