-- Apply to a dedicated AdaptTrail database before starting the hosted app.
-- This schema is private: do not add it to Supabase's exposed API schemas.
CREATE SCHEMA IF NOT EXISTS adapttrail_private;
REVOKE ALL ON SCHEMA adapttrail_private FROM PUBLIC, anon, authenticated;
CREATE TABLE IF NOT EXISTS adapttrail_private.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS adapttrail_private.drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL, country TEXT NOT NULL,
    problem TEXT NOT NULL, approach TEXT NOT NULL,
    conditions TEXT NOT NULL, source_id TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    user_id BIGINT REFERENCES adapttrail_private.users(id)
);
CREATE INDEX IF NOT EXISTS drafts_owner ON adapttrail_private.drafts(user_id);
ALTER TABLE adapttrail_private.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE adapttrail_private.drafts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA adapttrail_private FROM PUBLIC, anon, authenticated;
-- The server connects using the database owner; Flask enforces account ownership.
-- Browser clients never receive database credentials or access these tables directly.
