ALTER TABLE adapttrail_private.drafts ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','ongoing','completed'));
CREATE TABLE adapttrail_private.progress_entries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL REFERENCES adapttrail_private.drafts(id) ON DELETE CASCADE,
 entry_date TEXT NOT NULL, observation TEXT NOT NULL, measurement TEXT,
 unit TEXT NOT NULL, metric TEXT NOT NULL, period TEXT NOT NULL,
 entry_type TEXT NOT NULL CHECK (entry_type IN ('observation','baseline','follow-up')),
 created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX progress_project_date ON adapttrail_private.progress_entries(project_id,entry_date);
ALTER TABLE adapttrail_private.progress_entries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON adapttrail_private.progress_entries FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON adapttrail_private.progress_entries TO adapttrail_app;
GRANT USAGE,SELECT ON SEQUENCE adapttrail_private.progress_entries_id_seq TO adapttrail_app;
CREATE POLICY backend_access ON adapttrail_private.progress_entries FOR ALL TO adapttrail_app USING (true) WITH CHECK (true);
