-- Private checklist for the existing server-side account model.
-- Never expose adapttrail_private through the Data API.
CREATE TABLE adapttrail_private.project_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES adapttrail_private.drafts(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (char_length(btrim(title)) BETWEEN 1 AND 240),
    completed INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0,1)),
    archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0,1)),
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX tasks_project ON adapttrail_private.project_tasks(project_id,archived,id);
ALTER TABLE adapttrail_private.project_tasks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON adapttrail_private.project_tasks FROM PUBLIC,anon,authenticated;
REVOKE ALL ON SEQUENCE adapttrail_private.project_tasks_id_seq FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON adapttrail_private.project_tasks TO adapttrail_app;
GRANT USAGE,SELECT ON SEQUENCE adapttrail_private.project_tasks_id_seq TO adapttrail_app;
-- Flask verifies the signed-in user's ownership before every read or mutation.
CREATE POLICY backend_access ON adapttrail_private.project_tasks
    FOR ALL TO adapttrail_app USING (true) WITH CHECK (true);
