CREATE TABLE adapttrail_private.assessments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES adapttrail_private.users(id),
 project_id BIGINT REFERENCES adapttrail_private.drafts(id) ON DELETE CASCADE,
 approach TEXT NOT NULL, inputs TEXT NOT NULL, result TEXT NOT NULL,
 rule_version TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX assessments_owner ON adapttrail_private.assessments(user_id);
CREATE INDEX assessments_project ON adapttrail_private.assessments(project_id);
ALTER TABLE adapttrail_private.assessments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON adapttrail_private.assessments FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON adapttrail_private.assessments TO adapttrail_app;
GRANT USAGE,SELECT ON SEQUENCE adapttrail_private.assessments_id_seq TO adapttrail_app;
CREATE POLICY backend_access ON adapttrail_private.assessments FOR ALL TO adapttrail_app USING (true) WITH CHECK (true);
